baseURL: "https://gnakman.github.io/" 
title: Nam Kyun Kang
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Data
          url: data/
          weight: 1 
        - name: Books
          url: books/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3

        

params:
    description: "Is this thing on?"
    author: Nam Kyun Kang
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: false
    disableThemeToggle: false
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Nam Kyun Kang
          subtitle: "I am an aerodynamicist with a passion in ground vehicle aerodynamics and motorsports. I hope to use this site to chronicle my career and documents some of the things that I have learn along the way."
          imageUrl: "Profile.jpg"
          imageWidth: 400
          imageHeight: 400
          buttons:
            - name: Data #Misc
              url: data/ #Misc
            - name: Books # Project
              url: books/ # Project
            - name: Courses # Aerodynamics
              url: courses/ # Aerodynamics

    socialIcons:
        - name: CV
          url: https://www.linkedin.com/in/nam-kang-5450b4254/
        - name: Email
          url: nkkang@gmail.com
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=DIjPHxgAAAAJ&hl=en
        - name: GitHub
          url: https://github.com/Gnakman


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Nam Kyun Kang"
      icon: favicon.ico
      iconHeight: 18

markup:
  blackFriday:
    angledQuotes: false
    extensions: null
    extensionsMask: null
    footnoteAnchorPrefix: ""
    footnoteReturnLinkContents: ""
    fractions: true
    hrefTargetBlank: false
    latexDashes: true
    nofollowLinks: false
    noreferrerLinks: false
    plainIDAnchors: true
    skipHTML: false
    smartDashes: true
    smartypants: true
    smartypantsQuotesNBSP: false
    taskLists: true
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
      autoHeadingIDType: github
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    guessSyntax: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: autumn
    tabWidth: 4
  tableOfContents:
    endLevel: 2
    ordered: false
    startLevel: 2
